language: php
php:
  - '5.6'
  - '7.2'
before_script:
  - composer require --dev phpunit/phpunit
  - ./vendor/bin/phpunit --version
script:
  ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests